processed 18 tasks

init:
A: object(100)

task 1 'publish'. lines 8-115:
created: object(105)
written: object(104)

task 2 'run'. lines 117-117:
created: object(107)
written: object(106)

task 3 'run'. lines 119-123:
written: object(108)
deleted: object(107)

task 4 'run'. lines 125-125:
created: object(110)
written: object(109)

task 5 'run'. lines 127-127:
created: object(112), object(113)
written: object(110), object(111)

task 6 'run'. lines 129-133:
Error: Object 0x032f88b6c64f0b334f8b020b385d08aa9df5c5625f1df486ace408ebf6096f6e is owned by object 0xf82d67caa424708f3f28fe5146d03bd9c1617bab2ba5142e8545541f41fe7d8d. Objects owned by other objects cannot be used as input arguments.

task 7 'run'. lines 135-135:
created: object(116)
written: object(115)

task 8 'run'. lines 137-140:
Error: Transaction Effects Status: Invalid command argument at 0. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: TypeMismatch }, source: None, command: Some(1) } }

task 9 'run'. lines 142-142:
created: object(119)
written: object(118)

task 10 'run'. lines 144-144:
created: object(121)
written: object(120)

task 11 'run'. lines 146-149:
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(0) } }

task 12 'run'. lines 151-151:
created: object(124)
written: object(123)

task 13 'run'. lines 153-156:
Error: Transaction Effects Status: Invalid command argument at 0. Immutable and shared objects cannot be passed by-value.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidObjectByValue }, source: None, command: Some(0) } }

task 14 'run'. lines 158-158:
created: object(127)
written: object(126)

task 15 'run'. lines 160-163:
Error: Transaction Effects Status: Invalid command argument at 0. Invalid usage of already taken value. There is now no value available at this location
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidUsageOfTakenValue }, source: None, command: Some(1) } }

task 16 'run'. lines 165-165:
created: object(130)
written: object(129)

task 17 'run'. lines 167-167:
Error: Transaction Effects Status: Invalid command argument at 0. Invalid usage of already taken value. There is now no value available at this location
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidUsageOfTakenValue }, source: None, command: Some(1) } }
